name: mobilicis_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_custom_carousel_slider: ^1.2.0
  http: ^1.1.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/brands/
